# Auto-label PRs based on changed files (labeler v5 format)

cli:
  - changed-files:
      - any-glob-to-any-file:
          - src/components/cli/**/*
          - src/utils/cli/**/*

renderer:
  - changed-files:
      - any-glob-to-any-file: src/renderer/**/*

components:
  - changed-files:
      - any-glob-to-any-file: src/components/**/*

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - docs/**/*

build:
  - changed-files:
      - any-glob-to-any-file:
          - build.config.ts
          - babel.config.js
          - tsconfig*.json

tests:
  - changed-files:
      - any-glob-to-any-file:
          - src/__tests__/**/*
          - '**/*.test.ts'
          - '**/*.test.tsx'
          - vitest.config.ts

examples:
  - changed-files:
      - any-glob-to-any-file: examples/**/*

config:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - .husky/**/*
          - .lintstagedrc.js
          - eslint.config.mjs
          - package.json
